[package]
name = "scalib"
version = "0.1.0"
authors = ["obronchain <olivier.bronchain@uclouvain.be>"]
edition = "2018"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[dependencies]
numpy = "0.13.0"
rayon = "1.5.0"
num-integer = "0.1.42"
indicatif = "0.15.0"
ndarray = { version = "0.15.1", features = ["rayon","blas"] }
itertools = "0.10.0"
ndarray-stats = "0.4.0"
ndarray-linalg = "0.13.1"
lapacke = "0.3.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "belief_propagation"
harness = false

